# This file serves as a base to build a custom configuration

evmNetworkId: 100
incentives:
  contentEvaluator: {}
  userExtractor: {}
  dataPurge: {}
  formattingEvaluator: {}
  payment: {}
  reviewIncentivizer: {}
  simplificationIncentivizer: {}
  githubComment:
    post: false
    debug: false
